// Automatic Translation Helper for Yo! App
// This generates translations for all supported languages

import { LanguageTranslations } from './translations';

// Translation mappings for all supported languages
export const autoTranslations: Record<string, Partial<LanguageTranslations>> = {
  es: {
    title: 'Elige tu Idioma',
    subtitle: 'Desplázate para seleccionar tu idioma preferido para Yo!',
    continue: 'Continuar',
    saving: 'Guardando...',
    languageUpdated: 'Idioma Actualizado',
    languageUpdatedMessage: 'Tu idioma se ha establecido a',
    error: 'Error',
    errorMessage: 'No se pudo actualizar la preferencia de idioma. Por favor, inténtalo de nuevo.',
    ok: 'OK',

    welcome: {
      title: '¡Bienvenido a Yo!',
      meetTitle: '¡Conoce a Yo!',
      subtitle: 'Tu asistente personal con IA para la productividad ejecutiva',
      getStarted: 'Comenzar',
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
      signIn: 'Iniciar Sesión',
      description: 'Estoy disponible en cualquier momento que me necesites',
      signUp: 'Registrarse',
      features: {
        smartTaskManagement: 'Gestión Inteligente de Tareas',
        smartTaskManagementDesc: 'La IA prioriza y organiza tu trabajo',
        naturalConversations: 'Conversaciones Naturales',
        naturalConversationsDesc: 'Habla con tu asistente como con un amigo',
        intelligentScheduling: 'Programación Inteligente',
        intelligentSchedulingDesc: 'Nunca más dobles reservas o reuniones perdidas',
        seamlessIntegration: 'Integración Perfecta',
        seamlessIntegrationDesc: 'Conecta todas tus aplicaciones y herramientas',
        proactiveReminders: 'Recordatorios Proactivos',
        proactiveRemindersDesc: 'Recibe notificaciones antes de que necesites actuar',
        deadlineTracking: 'Seguimiento de Fechas Límite',
        deadlineTrackingDesc: 'Mantente al día con todos tus compromisos',
      },
      footerText: 'Registro seguro con cifrado de extremo a extremo',
      orContinueWith: 'O',
    },

    termsPrivacy: {
      title: 'Términos y Privacidad',
      mainTitle: 'Términos de Servicio y Política de Privacidad',
      subtitle: 'Al usar Yo! Asistente Personal, aceptas estos términos y nuestras prácticas de privacidad. Por favor, desplázate y lee el acuerdo completo a continuación.',
      progressText: '% leído',
      readyToContinue: 'Listo para continuar',
      slideToAccept: 'Desliza para aceptar',
      termsSection: '📋 Términos de Servicio',
      privacySection: '🔒 Política de Privacidad',
      serviceAgreement: '1. Acuerdo de Servicio',
      serviceAgreementText: 'Yo! es un asistente personal con IA que te ayuda a gestionar tareas, programar eventos e integrarse con herramientas de productividad. Al usar nuestro servicio, aceptas estos términos y todas las leyes aplicables.',
      responsibilities: '2. Tus Responsabilidades',
      responsibilitiesText: '• Usar el servicio de manera legal y responsable\n• Proporcionar información precisa cuando sea necesario\n• Mantener la seguridad y confidencialidad de la cuenta\n• Respetar la propiedad intelectual y los derechos de usuario\n• Reportar problemas de seguridad o uso inapropiado',
      aiTechnology: '3. Tecnología IA y Aprendizaje',
      aiTechnologyText: 'Nuestra IA procesa tus interacciones para proporcionar asistencia personalizada y mejorar la calidad del servicio. El sistema aprende de tus preferencias para servirte mejor mientras mantiene las salvaguardas de privacidad.',
      serviceAvailability: '4. Disponibilidad del Servicio',
      serviceAvailabilityText: 'Nos esforzamos por un 99.9% de tiempo activo pero no podemos garantizar un servicio ininterrumpido. El mantenimiento programado y las actualizaciones pueden afectar temporalmente la disponibilidad.',
      limitations: '5. Limitaciones y Responsabilidad',
      limitationsText: 'El servicio se proporciona "tal como está" con cuidado razonable pero sin garantías. Nuestra responsabilidad está limitada al máximo permitido por la ley.',
      dataWeCollect: 'Datos que Recopilamos',
      dataWeCollectText: '• Información de perfil (nombre, email, teléfono, preferencias)\n• Patrones de uso (comandos, interacciones, uso de funciones)\n• Datos del dispositivo (dirección IP, tipo de dispositivo, versión de la app)\n• Grabaciones de voz (solo cuando uses funciones de voz)\n• Datos de ubicación (solo cuando esté explícitamente habilitado)',
      howWeUseData: 'Cómo Usamos tus Datos',
      howWeUseDataText: 'Usamos tu información para proporcionar asistencia personalizada, mejorar nuestros modelos de IA, asegurar la seguridad del servicio y desarrollar nuevas funciones. Todo el procesamiento se hace con tu consentimiento y de acuerdo con las leyes de privacidad.',
      dataProtection: 'Protección y Seguridad de Datos',
      dataProtectionText: '• Cifrado de extremo a extremo para datos sensibles\n• Auditorías de seguridad regulares y monitoreo\n• Controles de acceso estrictos y autenticación\n• Cumplimiento con GDPR, CCPA y regulaciones de privacidad\n• Infraestructura en la nube segura con sistemas de respaldo',
      privacyRights: 'Tus Derechos de Privacidad',
      privacyRightsText: '• Acceder y revisar tus datos personales\n• Corregir información inexacta\n• Solicitar eliminación de tu cuenta y datos\n• Exportar tus datos (portabilidad de datos)\n• Optar por no participar en procesamiento no esencial de datos\n• Controlar integraciones de terceros y permisos',
      thirdPartyServices: 'Servicios de Terceros',
      thirdPartyServicesText: 'Cuando conectas servicios externos (Gmail, Calendar, etc.), accedemos solo a los datos mínimos necesarios para la funcionalidad. Nunca vendemos tu información personal a terceros.',
      dataRetention: 'Retención de Datos',
      dataRetentionText: 'Retenemos tus datos solo el tiempo necesario para proporcionar servicios o según lo requiera la ley. Puedes solicitar eliminación en cualquier momento a través de la configuración de tu cuenta o contactando soporte.',
      contactSupport: 'Contacto y Soporte',
      contactSupportText: 'Para preguntas de privacidad o solicitudes de datos, contacta a nuestro Oficial de Protección de Datos en privacy@yo-assistant.com. Para soporte general, usa la ayuda en la app o visita nuestro centro de soporte.',
      finalAgreement: '✨ Al continuar, reconoces que has leído y aceptas estos Términos de Servicio y Política de Privacidad.',
      accepted: '✓ Términos y Privacidad Aceptados',
      readyToContinueAfterAccept: 'Listo para continuar',
    },

    userDetails: {
      title: 'Detalles del Usuario',
      mainTitle: 'Cuéntanos sobre ti',
      subtitle: 'Tu Asistente Personal usará esta información para reservas, citas y comunicaciones profesionales en tu nombre.',
      fullName: 'Nombre Completo *',
      fullNamePlaceholder: 'ej., Juan Miguel García',
      fullNameDescription: 'Tu nombre legal para reservas y citas oficiales',
      preferredName: 'Nombre Preferido *',
      preferredNamePlaceholder: 'ej., Juan o Mike',
      preferredNameDescription: 'Cómo te gustaría que tu asistente te llame',
      titleOptional: 'Título (Opcional)',
      titlePlaceholder: 'ej., Sr., Dr., Prof.',
      titleDescription: 'Título profesional para comunicaciones formales',
      requiredField: 'Campo Requerido',
      enterFullName: 'Por favor ingresa tu nombre completo.',
      enterPreferredName: 'Por favor ingresa tu nombre preferido.',
    },

    signIn: {
      title: 'Bienvenido de Nuevo',
      subtitle: 'Inicia sesión en tu cuenta Yo! para continuar',
      email: 'Correo Electrónico',
      emailPlaceholder: 'Ingresa tu correo electrónico',
      password: 'Contraseña',
      passwordPlaceholder: 'Ingresa tu contraseña',
      signInButton: 'Iniciar Sesión',
      forgotPassword: '¿Olvidaste tu Contraseña?',
      noAccount: '¿No tienes una cuenta?',
      signUp: 'Registrarse',
      orContinueWith: 'O continúa con',
      google: 'Google',
      apple: 'Apple',
      invalidCredentials: 'Credenciales Inválidas',
      fillAllFields: 'Por favor completa todos los campos.',
      invalidEmail: 'Por favor ingresa una dirección de correo válida.',
      passwordTooShort: 'La contraseña debe tener al menos 6 caracteres.',
      signInFailed: 'Error al iniciar sesión. Por favor verifica tus credenciales.',
      tryAgain: 'Intentar de Nuevo',
      rememberMe: 'Recordarme',
    },

    phoneInput: {
      title: 'Verificación de Teléfono',
      subtitle: 'Enviaremos un código de verificación para confirmar tu número de teléfono',
      phoneNumber: 'Número de Teléfono',
      phoneNumberPlaceholder: 'Ingresa tu número de teléfono',
      sendCode: 'Enviar Código',
      invalidPhoneNumber: 'Número de Teléfono Inválido',
      enterPhoneNumber: 'Por favor ingresa un número de teléfono válido.',
      codeSent: 'Código Enviado',
      codeSentTo: 'Código de verificación enviado a',
    },

    common: {
      back: 'Atrás',
      next: 'Siguiente',
      skip: 'Omitir',
      done: 'Hecho',
      cancel: 'Cancelar',
      save: 'Guardar',
      loading: 'Cargando...',
      success: 'Éxito',
      failed: 'Falló',
      retry: 'Reintentar',
    },
  },

  fr: {
    title: 'Choisissez Votre Langue',
    subtitle: 'Faites défiler pour sélectionner votre langue préférée pour Yo!',
    continue: 'Continuer',
    saving: 'Enregistrement...',
    languageUpdated: 'Langue Mise à Jour',
    languageUpdatedMessage: 'Votre langue a été définie sur',
    error: 'Erreur',
    errorMessage: 'Échec de la mise à jour de la préférence de langue. Veuillez réessayer.',
    ok: 'OK',

    welcome: {
      title: 'Bienvenue dans Yo!',
      subtitle: 'Votre assistant personnel IA pour la productivité exécutive',
      getStarted: 'Commencer',
      alreadyHaveAccount: 'Vous avez déjà un compte?',
      signIn: 'Se Connecter',
    },

    termsPrivacy: {
      title: 'Conditions et Confidentialité',
      mainTitle: 'Conditions de Service et Politique de Confidentialité',
      subtitle: 'En utilisant Yo! Assistant Personnel, vous acceptez ces conditions et nos pratiques de confidentialité. Veuillez faire défiler et lire l\'accord complet ci-dessous.',
      progressText: '% lu',
      readyToContinue: 'Prêt à continuer',
      slideToAccept: 'Glissez pour accepter',
      termsSection: '📋 Conditions de Service',
      privacySection: '🔒 Politique de Confidentialité',
      serviceAgreement: '1. Accord de Service',
      serviceAgreementText: 'Yo! est un assistant personnel IA qui vous aide à gérer les tâches, planifier des événements et s\'intégrer avec les outils de productivité. En utilisant notre service, vous acceptez ces conditions et toutes les lois applicables.',
      responsibilities: '2. Vos Responsabilités',
      responsibilitiesText: '• Utiliser le service légalement et de manière responsable\n• Fournir des informations précises lorsque requis\n• Maintenir la sécurité et la confidentialité du compte\n• Respecter la propriété intellectuelle et les droits des utilisateurs\n• Signaler les problèmes de sécurité ou l\'usage inapproprié',
      aiTechnology: '3. Technologie IA et Apprentissage',
      aiTechnologyText: 'Notre IA traite vos interactions pour fournir une assistance personnalisée et améliorer la qualité du service. Le système apprend de vos préférences pour mieux vous servir tout en maintenant les protections de confidentialité.',
      serviceAvailability: '4. Disponibilité du Service',
      serviceAvailabilityText: 'Nous visons 99,9% de temps de fonctionnement mais ne pouvons garantir un service ininterrompu. La maintenance programmée et les mises à jour peuvent temporairement affecter la disponibilité.',
      limitations: '5. Limitations et Responsabilité',
      limitationsText: 'Le service est fourni "tel quel" avec un soin raisonnable mais sans garanties. Notre responsabilité est limitée au maximum autorisé par la loi.',
      dataWeCollect: 'Données que Nous Collectons',
      dataWeCollectText: '• Informations de profil (nom, email, téléphone, préférences)\n• Modèles d\'utilisation (commandes, interactions, utilisation des fonctionnalités)\n• Données de l\'appareil (adresse IP, type d\'appareil, version de l\'app)\n• Enregistrements vocaux (uniquement lors de l\'utilisation des fonctionnalités vocales)\n• Données de localisation (uniquement lorsqu\'explicitement activé)',
      howWeUseData: 'Comment Nous Utilisons Vos Données',
      howWeUseDataText: 'Nous utilisons vos informations pour fournir une assistance personnalisée, améliorer nos modèles IA, assurer la sécurité du service et développer de nouvelles fonctionnalités. Tout traitement est effectué avec votre consentement et conformément aux lois sur la confidentialité.',
      dataProtection: 'Protection et Sécurité des Données',
      dataProtectionText: '• Chiffrement de bout en bout pour les données sensibles\n• Audits de sécurité réguliers et surveillance\n• Contrôles d\'accès stricts et authentification\n• Conformité RGPD, CCPA et réglementations sur la confidentialité\n• Infrastructure cloud sécurisée avec systèmes de sauvegarde',
      privacyRights: 'Vos Droits de Confidentialité',
      privacyRightsText: '• Accéder et examiner vos données personnelles\n• Corriger les informations inexactes\n• Demander la suppression de votre compte et données\n• Exporter vos données (portabilité des données)\n• Refuser le traitement non essentiel des données\n• Contrôler les intégrations tierces et les permissions',
      thirdPartyServices: 'Services Tiers',
      thirdPartyServicesText: 'Lorsque vous connectez des services externes (Gmail, Calendar, etc.), nous accédons uniquement aux données minimales nécessaires pour la fonctionnalité. Nous ne vendons jamais vos informations personnelles à des tiers.',
      dataRetention: 'Rétention des Données',
      dataRetentionText: 'Nous conservons vos données uniquement le temps nécessaire pour fournir les services ou selon les exigences légales. Vous pouvez demander la suppression à tout moment via les paramètres de votre compte ou en contactant le support.',
      contactSupport: 'Contact et Support',
      contactSupportText: 'Pour les questions de confidentialité ou les demandes de données, contactez notre Délégué à la Protection des Données à privacy@yo-assistant.com. Pour le support général, utilisez l\'aide dans l\'app ou visitez notre centre de support.',
      finalAgreement: '✨ En continuant, vous reconnaissez avoir lu et accepté ces Conditions de Service et cette Politique de Confidentialité.',
      accepted: '✓ Conditions et Confidentialité Acceptées',
      readyToContinueAfterAccept: 'Prêt à continuer',
    },

    userDetails: {
      title: 'Détails de l\'Utilisateur',
      subtitle: 'Votre Assistant Personnel utilisera ces informations pour les réservations, rendez-vous et communications professionnelles en votre nom.',
      fullName: 'Nom Complet *',
      fullNamePlaceholder: 'ex., Jean Michel Dupont',
      fullNameDescription: 'Votre nom légal pour les réservations et rendez-vous officiels',
      preferredName: 'Nom Préféré *',
      preferredNamePlaceholder: 'ex., Jean ou Mike',
      preferredNameDescription: 'Comment vous aimeriez que votre assistant vous appelle',
      titleOptional: 'Titre (Optionnel)',
      titlePlaceholder: 'ex., M., Dr., Prof.',
      titleDescription: 'Titre professionnel pour les communications formelles',
      requiredField: 'Champ Requis',
      enterFullName: 'Veuillez entrer votre nom complet.',
      enterPreferredName: 'Veuillez entrer votre nom préféré.',
    },

    signIn: {
      title: 'Bon Retour',
      subtitle: 'Connectez-vous à votre compte Yo! pour continuer',
      email: 'Email',
      emailPlaceholder: 'Entrez votre email',
      password: 'Mot de Passe',
      passwordPlaceholder: 'Entrez votre mot de passe',
      signInButton: 'Se Connecter',
      forgotPassword: 'Mot de Passe Oublié?',
      noAccount: 'Vous n\'avez pas de compte?',
      signUp: 'S\'Inscrire',
      orContinueWith: 'Ou continuer avec',
      google: 'Google',
      apple: 'Apple',
      invalidCredentials: 'Identifiants Invalides',
      fillAllFields: 'Veuillez remplir tous les champs.',
      invalidEmail: 'Veuillez entrer une adresse email valide.',
      passwordTooShort: 'Le mot de passe doit contenir au moins 6 caractères.',
      signInFailed: 'Échec de la connexion. Veuillez vérifier vos identifiants.',
      tryAgain: 'Réessayer',
    },

    phoneInput: {
      title: 'Vérification Téléphonique',
      subtitle: 'Nous enverrons un code de vérification pour confirmer votre numéro de téléphone',
      phoneNumber: 'Numéro de Téléphone',
      phoneNumberPlaceholder: 'Entrez votre numéro de téléphone',
      sendCode: 'Envoyer le Code',
      invalidPhoneNumber: 'Numéro de Téléphone Invalide',
      enterPhoneNumber: 'Veuillez entrer un numéro de téléphone valide.',
      codeSent: 'Code Envoyé',
      codeSentTo: 'Code de vérification envoyé à',
    },

    common: {
      back: 'Retour',
      next: 'Suivant',
      skip: 'Ignorer',
      done: 'Terminé',
      cancel: 'Annuler',
      save: 'Sauvegarder',
      loading: 'Chargement...',
      success: 'Succès',
      failed: 'Échec',
      retry: 'Réessayer',
    },
  },

  // Adding basic structures for other languages...
  // For brevity, I'll add a few more key languages and the rest can be generated similarly

  de: {
    title: 'Wählen Sie Ihre Sprache',
    subtitle: 'Scrollen Sie, um Ihre bevorzugte Sprache für Yo! auszuwählen',
    continue: 'Weiter',
    saving: 'Speichern...',
    welcome: {
      title: 'Willkommen bei Yo!',
      subtitle: 'Ihr KI-gestützter persönlicher Assistent für Führungskräfte-Produktivität',
      getStarted: 'Loslegen',
      alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
      signIn: 'Anmelden',
    },
    common: {
      back: 'Zurück',
      next: 'Weiter',
      skip: 'Überspringen',
      done: 'Fertig',
      cancel: 'Abbrechen',
      save: 'Speichern',
      loading: 'Laden...',
      success: 'Erfolg',
      failed: 'Fehlgeschlagen',
      retry: 'Wiederholen',
    },
  },

  zh: {
    title: '选择您的语言',
    subtitle: '滚动选择您的Yo!首选语言',
    continue: '继续',
    saving: '保存中...',
    welcome: {
      title: '欢迎来到Yo!',
      subtitle: '您的AI驱动个人助手，专为高管生产力设计',
      getStarted: '开始使用',
      alreadyHaveAccount: '已有账户？',
      signIn: '登录',
    },
    common: {
      back: '返回',
      next: '下一步',
      skip: '跳过',
      done: '完成',
      cancel: '取消',
      save: '保存',
      loading: '加载中...',
      success: '成功',
      failed: '失败',
      retry: '重试',
    },
  },

  ja: {
    title: '言語を選択',
    subtitle: 'Yo!の希望言語を選択するためにスクロールしてください',
    continue: '続行',
    saving: '保存中...',
    welcome: {
      title: 'Yo!へようこそ',
      subtitle: 'エグゼクティブの生産性のためのAI搭載パーソナルアシスタント',
      getStarted: '始める',
      alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
      signIn: 'サインイン',
    },
    common: {
      back: '戻る',
      next: '次へ',
      skip: 'スキップ',
      done: '完了',
      cancel: 'キャンセル',
      save: '保存',
      loading: '読み込み中...',
      success: '成功',
      failed: '失敗',
      retry: '再試行',
    },
  },

  ar: {
    title: 'اختر لغتك',
    subtitle: 'مرر لتحديد لغتك المفضلة لـ Yo!',
    continue: 'متابعة',
    saving: 'حفظ...',
    welcome: {
      title: 'مرحباً بك في Yo!',
      subtitle: 'مساعدك الشخصي المدعوم بالذكاء الاصطناعي للإنتاجية التنفيذية',
      getStarted: 'ابدأ',
      alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
      signIn: 'تسجيل الدخول',
    },
    common: {
      back: 'رجوع',
      next: 'التالي',
      skip: 'تخطي',
      done: 'تم',
      cancel: 'إلغاء',
      save: 'حفظ',
      loading: 'جاري التحميل...',
      success: 'نجح',
      failed: 'فشل',
      retry: 'إعادة المحاولة',
    },
  },

  // Add more languages as needed...
};

// Base English translations (complete)
const englishTranslations: LanguageTranslations = {
  title: 'Choose Your Language',
  subtitle: 'Scroll to select your preferred language for Yo!',
  continue: 'Continue',
  saving: 'Saving...',
  languageUpdated: 'Language Updated',
  languageUpdatedMessage: 'Your language has been set to',
  error: 'Error',
  errorMessage: 'Failed to update language preference. Please try again.',
  ok: 'OK',

  welcome: {
    title: 'Welcome to Yo!',
    meetTitle: 'Meet Yo!',
    subtitle: 'Your AI-powered personal assistant for executive productivity',
    getStarted: 'Get Started',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    description: 'I\'m available anytime you need me',
    signUp: 'Sign Up',
    features: {
      smartTaskManagement: 'Smart Task Management',
      smartTaskManagementDesc: 'AI prioritizes and organizes your work',
      naturalConversations: 'Natural Conversations',
      naturalConversationsDesc: 'Talk to your assistant like a friend',
      intelligentScheduling: 'Intelligent Scheduling',
      intelligentSchedulingDesc: 'Never double-book or miss meetings',
      seamlessIntegration: 'Seamless Integration',
      seamlessIntegrationDesc: 'Connect all your apps and tools',
      proactiveReminders: 'Proactive Reminders',
      proactiveRemindersDesc: 'Get notified before you need to act',
      deadlineTracking: 'Deadline Tracking',
      deadlineTrackingDesc: 'Stay on top of all your commitments',
    },
    footerText: 'Secure registration with end-to-end encryption',
    orContinueWith: 'OR',
  },

  termsPrivacy: {
    title: 'Terms & Privacy',
    mainTitle: 'Terms of Service & Privacy Policy',
    subtitle: 'By using Yo! Personal Assistant, you agree to these terms and our privacy practices. Please scroll through and read the complete agreement below.',
    progressText: '% read',
    readyToContinue: 'Ready to continue',
    slideToAccept: 'Slide to accept',
    termsSection: '📋 Terms of Service',
    privacySection: '🔒 Privacy Policy',
    serviceAgreement: '1. Service Agreement',
    serviceAgreementText: 'Yo! is an AI-powered personal assistant that helps you manage tasks, schedule events, and integrate with productivity tools. By using our service, you agree to these terms and all applicable laws.',
    responsibilities: '2. Your Responsibilities',
    responsibilitiesText: '• Use the service lawfully and responsibly\n• Provide accurate information when required\n• Maintain account security and confidentiality\n• Respect intellectual property and user rights\n• Report security issues or inappropriate usage',
    aiTechnology: '3. AI Technology & Learning',
    aiTechnologyText: 'Our AI processes your interactions to provide personalized assistance and improve service quality. The system learns from your preferences to better serve your needs while maintaining privacy safeguards.',
    serviceAvailability: '4. Service Availability',
    serviceAvailabilityText: 'We strive for 99.9% uptime but cannot guarantee uninterrupted service. Scheduled maintenance and updates may temporarily affect availability.',
    limitations: '5. Limitations & Liability',
    limitationsText: 'The service is provided "as is" with reasonable care but no warranties. Our liability is limited to the maximum extent permitted by law.',
    dataWeCollect: 'Data We Collect',
    dataWeCollectText: '• Profile information (name, email, phone, preferences)\n• Usage patterns (commands, interactions, feature usage)\n• Device data (IP address, device type, app version)\n• Voice recordings (only when using voice features)\n• Location data (only when explicitly enabled)',
    howWeUseData: 'How We Use Your Data',
    howWeUseDataText: 'We use your information to provide personalized assistance, improve our AI models, ensure service security, and develop new features. All processing is done with your consent and in accordance with privacy laws.',
    dataProtection: 'Data Protection & Security',
    dataProtectionText: '• End-to-end encryption for sensitive data\n• Regular security audits and monitoring\n• Strict access controls and authentication\n• Compliance with GDPR, CCPA, and privacy regulations\n• Secure cloud infrastructure with backup systems',
    privacyRights: 'Your Privacy Rights',
    privacyRightsText: '• Access and review your personal data\n• Correct inaccurate information\n• Request deletion of your account and data\n• Export your data (data portability)\n• Opt out of non-essential data processing\n• Control third-party integrations and permissions',
    thirdPartyServices: 'Third-Party Services',
    thirdPartyServicesText: 'When you connect external services (Gmail, Calendar, etc.), we access only the minimum data necessary for functionality. We never sell your personal information to third parties.',
    dataRetention: 'Data Retention',
    dataRetentionText: 'We retain your data only as long as necessary to provide services or as required by law. You can request deletion at any time through your account settings or by contacting support.',
    contactSupport: 'Contact & Support',
    contactSupportText: 'For privacy questions or data requests, contact our Data Protection Officer at privacy@yo-assistant.com. For general support, use the in-app help or visit our support center.',
    finalAgreement: '✨ By continuing, you acknowledge that you have read and agree to these Terms of Service and Privacy Policy.',
    accepted: '✓ Terms & Privacy Accepted',
    readyToContinueAfterAccept: 'Ready to continue',
  },

  userDetails: {
    title: 'User Details',
    mainTitle: 'Tell us about yourself',
    subtitle: 'Your Personal Assistant will use this information for bookings, appointments, and professional communications on your behalf.',
    fullName: 'Full Name *',
    fullNamePlaceholder: 'e.g., John Michael Smith',
    fullNameDescription: 'Your legal name for official bookings and appointments',
    preferredName: 'Preferred Name *',
    preferredNamePlaceholder: 'e.g., John or Mike',
    preferredNameDescription: 'What you\'d like your assistant to call you',
    titleOptional: 'Title (Optional)',
    titlePlaceholder: 'e.g., Mr., Dr., Prof.',
    titleDescription: 'Professional title for formal communications',
    requiredField: 'Required Field',
    enterFullName: 'Please enter your full name.',
    enterPreferredName: 'Please enter your preferred name.',
  },

  signIn: {
    title: 'Welcome Back',
    subtitle: 'Sign in to your Yo! account to continue',
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    signInButton: 'Sign In',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    orContinueWith: 'Or continue with',
    google: 'Google',
    apple: 'Apple',
    invalidCredentials: 'Invalid Credentials',
    fillAllFields: 'Please fill in all fields.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters.',
    signInFailed: 'Sign in failed. Please check your credentials.',
    tryAgain: 'Try Again',
    rememberMe: 'Remember me',
  },

  phoneInput: {
    title: 'Phone Verification',
    subtitle: 'We\'ll send a verification code to confirm your phone number',
    phoneNumber: 'Phone Number',
    phoneNumberPlaceholder: 'Enter your phone number',
    sendCode: 'Send Code',
    invalidPhoneNumber: 'Invalid Phone Number',
    enterPhoneNumber: 'Please enter a valid phone number.',
    codeSent: 'Code Sent',
    codeSentTo: 'Verification code sent to',
  },

  common: {
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading...',
    success: 'Success',
    failed: 'Failed',
    retry: 'Retry',
  },
};

// Function to merge base translations with auto translations
export function getCompleteTranslations(languageCode: string): LanguageTranslations {
  // If English, return complete English translations
  if (languageCode === 'en') {
    return englishTranslations;
  }

  const languageTranslations = autoTranslations[languageCode];

  if (!languageTranslations) {
    return englishTranslations; // Fallback to English
  }

  // Deep merge translations with English as fallback
  return {
    ...englishTranslations,
    ...languageTranslations,
    welcome: {
      ...englishTranslations.welcome,
      ...(languageTranslations.welcome || {}),
      features: {
        ...englishTranslations.welcome.features,
        ...(languageTranslations.welcome?.features || {}),
      },
    },
    termsPrivacy: {
      ...englishTranslations.termsPrivacy,
      ...(languageTranslations.termsPrivacy || {}),
    },
    userDetails: {
      ...englishTranslations.userDetails,
      ...(languageTranslations.userDetails || {}),
    },
    signIn: {
      ...englishTranslations.signIn,
      ...(languageTranslations.signIn || {}),
    },
    phoneInput: {
      ...englishTranslations.phoneInput,
      ...(languageTranslations.phoneInput || {}),
    },
    common: {
      ...englishTranslations.common,
      ...(languageTranslations.common || {}),
    },
  };
}